version: '3.7'

services:

  dev:
    container_name: flux-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true
    tty: true

  test:
    container_name: flux-app-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    # environment:
    #   - CI=true
    command: npm test

  prod:
    container_name: flux-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=production