name: CI
 
on:
  push:
    branches: [ master ]

env:
  BUCKET: flux.guilsantos.dev
 
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run: npm install

    - name: Tests
      run: npm test

    - name: Build
      run: npm build  

    - name: Configure gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default-credentials: true
    
    - name: Upload to bucket
      run: gsuit -m rsync -R ./build gs://"$BUCKET"

    - name: Make files public
      run: gsuit -m acl ch -R -u AllUsers:R gs://"$BUCKET"

    - name: Configure cash directives
      run: |
        gsuit -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}
        gsuit setmeta -h "Cache-Control:no-cash, no-store" gs://"$BUCKET"/index.html
